### ISSUE TITLE
Does this library works on Angular 9?

### ISSUE THREAD

**Issue by fisasi1610** [Flo0806/ngx-explorer-dnd#1]
Greetings, im very interested in using your library to solve the grid drag and drop sorting issue im facing right now with angular material,
my only concern is that im using version 9 of angular and I was wondering if this library is going to work on my version.

Greetings, and hope to know from you.

**Comment by Flo0806** [comment]
Hello!

Thx for using it! The thing is, we have build it on Angular 15, but I think it will works on Angular < 15. In a few days an update will come and I think then it will possible to use it in lower versions like 15. In best case in version 9.

From now you can visit https://ngx-explorer-dnd.fh-softdev.de/ to read the documentation and change logs. But I will answer you here when we ready and published the working release.

Greetings, Flo

**Comment by Flo0806** [comment]
Hello!

the version 1.0.0-alpha.11 is build on Angular 9.1.11. You can try it!
